# Titre et description du site
title: "Guide du Développeur Scientifique"
description: "Accompagnement pour l'acquisition des connaissances fondamentales et bonnes pratiques du développement logiciel à des fins scientifiques."

# URL du site (mettre votre domaine personnalisé)
url: "https://yajeddig.github.io"
baseurl: "/Guide-du-Developpeur-Scientifique"  # Notez le slash initial

# Thème utilisé 
remote_theme: pages-themes/hacker@v0.2.0

# Plugins Jekyll supplémentaires (facultatif)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Informations sur l'auteur (à personnaliser)
author:
  name: "Younes AJEDDIG"
  email: "younes.ajeddig@live.fr"

# Configuration Markdown
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
