# Titre et description du site
title: "Guide du Développeur Scientifique"
description: "Accompagnement pour l'acquisition des connaissances fondamentales et bonnes pratiques du développement logiciel à des fins scientifiques."

# URL du site (mettre votre domaine personnalisé)
url: "https://yajeddig.github.io/Guide-du-Developpeur-Scientifique/"
baseurl: ""  # Laisser vide si le site est à la racine

# Thème utilisé (ici le thème Hacker via remote_theme)
theme: hacker

# Plugins Jekyll (fusion des plugins nécessaires)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Informations sur l'auteur (à personnaliser)
author:
  name: "Younes AJEDDIG"
  email: "younes.ajeddig@live.fr"

# Configuration Markdown
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown
